version: "3"
services:
    nginx:
    #     image: registry.cn-shanghai.aliyuncs.com/hellodock/nginx:latest
        image: nginx:latest
        build: .
        restart: always
        # volumes:
        #     - ./conf/nginx.conf:/etc/nginx/nginx.conf
        #     - ./conf/conf.d:/etc/nginx/conf.d
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
        ports:
            - 80:80
        networks:
            - nginx

networks:
    nginx:
        driver: bridge
